version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_TestPublish_2209Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: DADA_GlobalVariable1
  gitServerName: rimaSCName
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_testpublish_2209.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_TestPublish_2209Project
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: project.siqa_testpublish_2209.integrations:Sum
  packages:
  - name: SIQA_TestPublish_2209Project
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: project.siqa_testpublish_2209.integrations:deepclonetest
  packages:
  - name: SIQA_TestPublish_2209Project
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
